test = {   'name': 'q1b',
    'points': 1,
    'suites': [   {   'cases': [   {   'code': '>>> list_sum([], [])\n',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> list_sum([1], [1])\n',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> list_sum([-1], [1])\n',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> list_sum([1], [-1])\n',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> list_sum([1, 2, 3], [1, 2, '
                                               '3])\n',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> list_sum([1, 5, 2], [3, 6, '
                                               '6])\n',
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
