test = {   'name': 'q1b',
    'points': 1,
    'suites': [   {   'cases': [   {   'code': '>>> type(X)== np.ndarray\nTrue',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> type(Y)== np.ndarray\nTrue',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> 0<X[0]<100\narray([ True])',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> Y[0]==1 or Y[0]== 0\nTrue',
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
